package binaryconverter;

import static binaryconverter.BinaryConverter.toBinary;
import static binaryconverter.BinaryConverter.toDecimal;
import javax.swing.JOptionPane;

public class Converter extends javax.swing.JFrame
{
    public Converter()
    {
        initComponents();
        txtOutput.setEditable(false);
        frmHelp.setVisible(false);
        frmHelp.setSize(243,235);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmHelp = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnBinToDec = new javax.swing.JToggleButton();
        btnDecToBin = new javax.swing.JToggleButton();
        lblInput = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        lblOutput = new javax.swing.JLabel();
        txtOutput = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        lblSelecOpt = new javax.swing.JLabel();

        frmHelp.setTitle("Ayuda");
        frmHelp.setResizable(false);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("                      Conversor\n\nEsta aplicación permite realizar\nconversiones entre los sistemas\nde numeración binario y decimal.\nFue pensado como una herramienta \npara el subneteo por lo que solo\npermite el ingreso de máximo un\nbyte (8 bits), esto es un rango del\n0 - 255.\n\nUso:\nPara usar la aplicación primero\nse debe seleccionar que tipo de\nconversión se realizará; para\nconvertir números decimales a\nbinarios seleccione:\n\"Decimal A Binario\"\npara el proceso inverso: \n\"Binario A Decimal\".\nProceda a llenar el campo\ndespues de la etiqueta\n\"Número\"\ny presione el botón\n\"Convertir\".\n\nNota:\nLos dígitos binarios se\nrepresentan únicamente con \"0\" y\n\"1\".\n");
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout frmHelpLayout = new javax.swing.GroupLayout(frmHelp.getContentPane());
        frmHelp.getContentPane().setLayout(frmHelpLayout);
        frmHelpLayout.setHorizontalGroup(
            frmHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );
        frmHelpLayout.setVerticalGroup(
            frmHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");
        setResizable(false);

        btnBinToDec.setText("Binario A Decimal");
        btnBinToDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinToDecActionPerformed(evt);
            }
        });

        btnDecToBin.setText("Decimal A Binario");
        btnDecToBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecToBinActionPerformed(evt);
            }
        });

        lblInput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInput.setText("Número");

        txtInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInputKeyPressed(evt);
            }
        });

        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutput.setText("Conversión");

        txtOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnConvert.setText("Convertir");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        btnHelp.setText("?");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        lblSelecOpt.setText("Seleciona una opción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSelecOpt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHelp)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDecToBin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(btnBinToDec))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInput, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInput)
                                    .addComponent(txtOutput))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConvert)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHelp)
                    .addComponent(lblSelecOpt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBinToDec, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDecToBin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblInput)
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConvert))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutput)
                    .addComponent(txtOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDecToBinActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btnDecToBinActionPerformed
        // TODO add your handling code here:
        btnBinToDec.setSelected(false);
        txtInput.setText("");
        txtOutput.setText("");
        txtInput.requestFocus();
        lblSelecOpt.setVisible(false);
    }//GEN-LAST:event_btnDecToBinActionPerformed

    private void btnBinToDecActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btnBinToDecActionPerformed
        // TODO add your handling code here:
        btnDecToBin.setSelected(false);
        txtInput.setText("");
        txtOutput.setText("");
        txtInput.requestFocus();
        lblSelecOpt.setVisible(false);
    }//GEN-LAST:event_btnBinToDecActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
        if(btnDecToBin.isSelected() && isFieldFilled())
        {
            if(isDecimalValid())
            {
                txtOutput.setText(toBinary(Integer.valueOf(txtInput.getText())));
            }
        }
        else if(btnBinToDec.isSelected() && isFieldFilled())
        {
            if(isBinaryValid())
            {
                txtOutput.setText(toDecimal(txtInput.getText()));
            }
        }
        txtInput.requestFocus();
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        frmHelp.setVisible(true);
        frmHelp.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_txtInputActionPerformed

    private void txtInputKeyPressed(java.awt.event.KeyEvent evt)
    {//GEN-FIRST:event_txtInputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        { btnConvert.doClick(); }
    }//GEN-LAST:event_txtInputKeyPressed

    private boolean isDecimalValid()
    {
        try
        {
            int numIn = Integer.valueOf(txtInput.getText());
        }
        catch (NumberFormatException e) {
            txtInput.setText("");
            txtOutput.setText("");
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entero entre 0 - 255", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        int numIn = Integer.valueOf(txtInput.getText());
        if(numIn < 0 || numIn > 255)
        {
            txtInput.setText("");
            txtOutput.setText("");
            JOptionPane.showMessageDialog(this, "El número entero debe de estar en el rango de 0 - 255", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean isBinaryValid()
    {
        if (txtInput.getText().length() <= 8)
        {
            boolean flag = false;
            for(int i = 0; i < txtInput.getText().length(); i++)
            {
                if(txtInput.getText().charAt(i) != '0' &&
                 txtInput.getText().charAt(i) != '1')
                {
                    flag = true;
                    break;
                }
            }
            if(flag == true)
            {
                txtInput.setText("");
                txtOutput.setText("");
                JOptionPane.showMessageDialog(this, "Debe ingresar digitos binarios", "ERROR", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        else
        {
            txtInput.setText("");
            txtOutput.setText("");
            JOptionPane.showMessageDialog(this, "El numero debe ser de 8 digitos binarios", "ERROR",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean isFieldFilled()
    {
        if(txtInput.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else
        {
            return true;
        }
    }

    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBinToDec;
    private javax.swing.JButton btnConvert;
    private javax.swing.JToggleButton btnDecToBin;
    private javax.swing.JButton btnHelp;
    private javax.swing.JFrame frmHelp;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblSelecOpt;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtOutput;
    // End of variables declaration//GEN-END:variables
}
